name: Webhook Trigger

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: "An example input"
        required: false
        default: "default value"

jobs:
  run-on-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Echo webhook trigger'
        env:
          STRAVA_ID: ${{ vars.STRAVA_ID }}
          STRAVA_SECRET: ${{ secrets.STRAVA_SECRET }}
          STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}
        run: |
          npm run build

      - name: Commit and push updated SVG
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update SVG via webhook trigger"
          git push origin main
